<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="To_Do_List" Id="{6aec0084-8702-45f9-8721-b3ccb8499ec5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM To_Do_List
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*

Create Wireless Enable
OR Joystick buttons

Add Joystick Estop to PLC estop

Calibrate Joystick















*)]]></ST>
    </Implementation>
    <LineIds Name="To_Do_List">
      <LineId Id="3" Count="22" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>